//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRM.SMSService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BrandNames", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class BrandNames : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenderField;
        
        private System.Nullable<bool> IsADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NotesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Sender {
            get {
                return this.SenderField;
            }
            set {
                if ((object.ReferenceEquals(this.SenderField, value) != true)) {
                    this.SenderField = value;
                    this.RaisePropertyChanged("Sender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<bool> IsAD {
            get {
                return this.IsADField;
            }
            set {
                if ((this.IsADField.Equals(value) != true)) {
                    this.IsADField = value;
                    this.RaisePropertyChanged("IsAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Notes {
            get {
                return this.NotesField;
            }
            set {
                if ((object.ReferenceEquals(this.NotesField, value) != true)) {
                    this.NotesField = value;
                    this.RaisePropertyChanged("Notes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsMessageItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SmsMessageItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private System.Nullable<int> IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BrandNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsTypeField;
        
        private System.Nullable<int> SmsCountField;
        
        private System.Nullable<int> SendCountField;
        
        private System.Nullable<int> NotSendCountField;
        
        private System.Nullable<decimal> AmountField;
        
        private System.Nullable<System.DateTime> SendDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SmsGuidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GuidNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<int> ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Contents {
            get {
                return this.ContentsField;
            }
            set {
                if ((object.ReferenceEquals(this.ContentsField, value) != true)) {
                    this.ContentsField = value;
                    this.RaisePropertyChanged("Contents");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string BrandName {
            get {
                return this.BrandNameField;
            }
            set {
                if ((object.ReferenceEquals(this.BrandNameField, value) != true)) {
                    this.BrandNameField = value;
                    this.RaisePropertyChanged("BrandName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string SmsType {
            get {
                return this.SmsTypeField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsTypeField, value) != true)) {
                    this.SmsTypeField = value;
                    this.RaisePropertyChanged("SmsType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<int> SmsCount {
            get {
                return this.SmsCountField;
            }
            set {
                if ((this.SmsCountField.Equals(value) != true)) {
                    this.SmsCountField = value;
                    this.RaisePropertyChanged("SmsCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public System.Nullable<int> SendCount {
            get {
                return this.SendCountField;
            }
            set {
                if ((this.SendCountField.Equals(value) != true)) {
                    this.SendCountField = value;
                    this.RaisePropertyChanged("SendCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public System.Nullable<int> NotSendCount {
            get {
                return this.NotSendCountField;
            }
            set {
                if ((this.NotSendCountField.Equals(value) != true)) {
                    this.NotSendCountField = value;
                    this.RaisePropertyChanged("NotSendCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public System.Nullable<System.DateTime> SendDate {
            get {
                return this.SendDateField;
            }
            set {
                if ((this.SendDateField.Equals(value) != true)) {
                    this.SendDateField = value;
                    this.RaisePropertyChanged("SendDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string SmsGuid {
            get {
                return this.SmsGuidField;
            }
            set {
                if ((object.ReferenceEquals(this.SmsGuidField, value) != true)) {
                    this.SmsGuidField = value;
                    this.RaisePropertyChanged("SmsGuid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string GuidName {
            get {
                return this.GuidNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GuidNameField, value) != true)) {
                    this.GuidNameField = value;
                    this.RaisePropertyChanged("GuidName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SmsPhoneListItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class SmsPhoneListItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private long IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        private System.Nullable<decimal> PriceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<decimal> Price {
            get {
                return this.PriceField;
            }
            set {
                if ((this.PriceField.Equals(value) != true)) {
                    this.PriceField = value;
                    this.RaisePropertyChanged("Price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string TelName {
            get {
                return this.TelNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TelNameField, value) != true)) {
                    this.TelNameField = value;
                    this.RaisePropertyChanged("TelName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TopUpHistoryItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TopUpHistoryItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IDField;
        
        private System.Nullable<System.DateTime> TopUpDateField;
        
        private System.Nullable<decimal> AmountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TypeNameField;
        
        private System.Nullable<bool> ActiveField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ID {
            get {
                return this.IDField;
            }
            set {
                if ((this.IDField.Equals(value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> TopUpDate {
            get {
                return this.TopUpDateField;
            }
            set {
                if ((this.TopUpDateField.Equals(value) != true)) {
                    this.TopUpDateField = value;
                    this.RaisePropertyChanged("TopUpDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.Nullable<decimal> Amount {
            get {
                return this.AmountField;
            }
            set {
                if ((this.AmountField.Equals(value) != true)) {
                    this.AmountField = value;
                    this.RaisePropertyChanged("Amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string TypeName {
            get {
                return this.TypeNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TypeNameField, value) != true)) {
                    this.TypeNameField = value;
                    this.RaisePropertyChanged("TypeName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public System.Nullable<bool> Active {
            get {
                return this.ActiveField;
            }
            set {
                if ((this.ActiveField.Equals(value) != true)) {
                    this.ActiveField = value;
                    this.RaisePropertyChanged("Active");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SMSService.APISoap")]
    public interface APISoap {
        
        // CODEGEN: Generating message contract since element name aboutResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/about", ReplyAction="*")]
        CRM.SMSService.aboutResponse about(CRM.SMSService.aboutRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkClient", ReplyAction="*")]
        CRM.SMSService.checkClientResponse checkClient(CRM.SMSService.checkClientRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/changePassword", ReplyAction="*")]
        CRM.SMSService.changePasswordResponse changePassword(CRM.SMSService.changePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendSMS", ReplyAction="*")]
        CRM.SMSService.sendSMSResponse sendSMS(CRM.SMSService.sendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendRandomSMS", ReplyAction="*")]
        CRM.SMSService.sendRandomSMSResponse sendRandomSMS(CRM.SMSService.sendRandomSMSRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/sendRandomSMSDemo", ReplyAction="*")]
        CRM.SMSService.sendRandomSMSDemoResponse sendRandomSMSDemo(CRM.SMSService.sendRandomSMSDemoRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checksendSMS", ReplyAction="*")]
        CRM.SMSService.checksendSMSResponse checksendSMS(CRM.SMSService.checksendSMSRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/checkSMSRandom", ReplyAction="*")]
        CRM.SMSService.checkSMSRandomResponse checkSMSRandom(CRM.SMSService.checkSMSRandomRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/topup", ReplyAction="*")]
        CRM.SMSService.topupResponse topup(CRM.SMSService.topupRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBalance", ReplyAction="*")]
        CRM.SMSService.getBalanceResponse getBalance(CRM.SMSService.getBalanceRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getBrandNames", ReplyAction="*")]
        CRM.SMSService.getBrandNamesResponse getBrandNames(CRM.SMSService.getBrandNamesRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getListSMS", ReplyAction="*")]
        CRM.SMSService.getListSMSResponse getListSMS(CRM.SMSService.getListSMSRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getPhoneList", ReplyAction="*")]
        CRM.SMSService.getPhoneListResponse getPhoneList(CRM.SMSService.getPhoneListRequest request);
        
        // CODEGEN: Generating message contract since element name clientNo from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getTopupHistory", ReplyAction="*")]
        CRM.SMSService.getTopupHistoryResponse getTopupHistory(CRM.SMSService.getTopupHistoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aboutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="about", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.aboutRequestBody Body;
        
        public aboutRequest() {
        }
        
        public aboutRequest(CRM.SMSService.aboutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class aboutRequestBody {
        
        public aboutRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class aboutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="aboutResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.aboutResponseBody Body;
        
        public aboutResponse() {
        }
        
        public aboutResponse(CRM.SMSService.aboutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class aboutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aboutResult;
        
        public aboutResponseBody() {
        }
        
        public aboutResponseBody(string aboutResult) {
            this.aboutResult = aboutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkClientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkClient", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.checkClientRequestBody Body;
        
        public checkClientRequest() {
        }
        
        public checkClientRequest(CRM.SMSService.checkClientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkClientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        public checkClientRequestBody() {
        }
        
        public checkClientRequestBody(string clientNo, string clientPass) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkClientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkClientResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.checkClientResponseBody Body;
        
        public checkClientResponse() {
        }
        
        public checkClientResponse(CRM.SMSService.checkClientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkClientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int checkClientResult;
        
        public checkClientResponseBody() {
        }
        
        public checkClientResponseBody(int checkClientResult) {
            this.checkClientResult = checkClientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePassword", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.changePasswordRequestBody Body;
        
        public changePasswordRequest() {
        }
        
        public changePasswordRequest(CRM.SMSService.changePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string oldPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string newPass;
        
        public changePasswordRequestBody() {
        }
        
        public changePasswordRequestBody(string clientNo, string oldPass, string newPass) {
            this.clientNo = clientNo;
            this.oldPass = oldPass;
            this.newPass = newPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="changePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.changePasswordResponseBody Body;
        
        public changePasswordResponse() {
        }
        
        public changePasswordResponse(CRM.SMSService.changePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class changePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int changePasswordResult;
        
        public changePasswordResponseBody() {
        }
        
        public changePasswordResponseBody(int changePasswordResult) {
            this.changePasswordResult = changePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMS", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.sendSMSRequestBody Body;
        
        public sendSMSRequest() {
        }
        
        public sendSMSRequest(CRM.SMSService.sendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CRM.SMSService.ArrayOfString listPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isADs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string smsGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string guidName;
        
        public sendSMSRequestBody() {
        }
        
        public sendSMSRequestBody(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string sender, bool isADs, string title, string message, string smsGUID, string guidName) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.listPhone = listPhone;
            this.sender = sender;
            this.isADs = isADs;
            this.title = title;
            this.message = message;
            this.smsGUID = smsGUID;
            this.guidName = guidName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.sendSMSResponseBody Body;
        
        public sendSMSResponse() {
        }
        
        public sendSMSResponse(CRM.SMSService.sendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendSMSResult;
        
        public sendSMSResponseBody() {
        }
        
        public sendSMSResponseBody(int sendSMSResult) {
            this.sendSMSResult = sendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRandomSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRandomSMS", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.sendRandomSMSRequestBody Body;
        
        public sendRandomSMSRequest() {
        }
        
        public sendRandomSMSRequest(CRM.SMSService.sendRandomSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendRandomSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CRM.SMSService.ArrayOfString listPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string smsGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string guidName;
        
        public sendRandomSMSRequestBody() {
        }
        
        public sendRandomSMSRequestBody(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string title, string message, string smsGUID, string guidName) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.listPhone = listPhone;
            this.title = title;
            this.message = message;
            this.smsGUID = smsGUID;
            this.guidName = guidName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRandomSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRandomSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.sendRandomSMSResponseBody Body;
        
        public sendRandomSMSResponse() {
        }
        
        public sendRandomSMSResponse(CRM.SMSService.sendRandomSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendRandomSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendRandomSMSResult;
        
        public sendRandomSMSResponseBody() {
        }
        
        public sendRandomSMSResponseBody(int sendRandomSMSResult) {
            this.sendRandomSMSResult = sendRandomSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRandomSMSDemoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRandomSMSDemo", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.sendRandomSMSDemoRequestBody Body;
        
        public sendRandomSMSDemoRequest() {
        }
        
        public sendRandomSMSDemoRequest(CRM.SMSService.sendRandomSMSDemoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendRandomSMSDemoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CRM.SMSService.ArrayOfString listPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string smsGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string guidName;
        
        public sendRandomSMSDemoRequestBody() {
        }
        
        public sendRandomSMSDemoRequestBody(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string title, string message, string smsGUID, string guidName) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.listPhone = listPhone;
            this.title = title;
            this.message = message;
            this.smsGUID = smsGUID;
            this.guidName = guidName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendRandomSMSDemoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="sendRandomSMSDemoResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.sendRandomSMSDemoResponseBody Body;
        
        public sendRandomSMSDemoResponse() {
        }
        
        public sendRandomSMSDemoResponse(CRM.SMSService.sendRandomSMSDemoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class sendRandomSMSDemoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int sendRandomSMSDemoResult;
        
        public sendRandomSMSDemoResponseBody() {
        }
        
        public sendRandomSMSDemoResponseBody(int sendRandomSMSDemoResult) {
            this.sendRandomSMSDemoResult = sendRandomSMSDemoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checksendSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checksendSMS", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.checksendSMSRequestBody Body;
        
        public checksendSMSRequest() {
        }
        
        public checksendSMSRequest(CRM.SMSService.checksendSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checksendSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CRM.SMSService.ArrayOfString listPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sender;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public bool isADs;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string smsGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string guidName;
        
        public checksendSMSRequestBody() {
        }
        
        public checksendSMSRequestBody(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string sender, bool isADs, string title, string message, string smsGUID, string guidName) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.listPhone = listPhone;
            this.sender = sender;
            this.isADs = isADs;
            this.title = title;
            this.message = message;
            this.smsGUID = smsGUID;
            this.guidName = guidName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checksendSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checksendSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.checksendSMSResponseBody Body;
        
        public checksendSMSResponse() {
        }
        
        public checksendSMSResponse(CRM.SMSService.checksendSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checksendSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int checksendSMSResult;
        
        public checksendSMSResponseBody() {
        }
        
        public checksendSMSResponseBody(int checksendSMSResult) {
            this.checksendSMSResult = checksendSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkSMSRandomRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkSMSRandom", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.checkSMSRandomRequestBody Body;
        
        public checkSMSRandomRequest() {
        }
        
        public checkSMSRandomRequest(CRM.SMSService.checkSMSRandomRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkSMSRandomRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public CRM.SMSService.ArrayOfString listPhone;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string message;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string smsGUID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string guidName;
        
        public checkSMSRandomRequestBody() {
        }
        
        public checkSMSRandomRequestBody(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string title, string message, string smsGUID, string guidName) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.listPhone = listPhone;
            this.title = title;
            this.message = message;
            this.smsGUID = smsGUID;
            this.guidName = guidName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class checkSMSRandomResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="checkSMSRandomResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.checkSMSRandomResponseBody Body;
        
        public checkSMSRandomResponse() {
        }
        
        public checkSMSRandomResponse(CRM.SMSService.checkSMSRandomResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class checkSMSRandomResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int checkSMSRandomResult;
        
        public checkSMSRandomResponseBody() {
        }
        
        public checkSMSRandomResponseBody(int checkSMSRandomResult) {
            this.checkSMSRandomResult = checkSMSRandomResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class topupRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="topup", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.topupRequestBody Body;
        
        public topupRequest() {
        }
        
        public topupRequest(CRM.SMSService.topupRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class topupRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public decimal amount;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string secureCode;
        
        public topupRequestBody() {
        }
        
        public topupRequestBody(string clientNo, string clientPass, decimal amount, string secureCode) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.amount = amount;
            this.secureCode = secureCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class topupResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="topupResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.topupResponseBody Body;
        
        public topupResponse() {
        }
        
        public topupResponse(CRM.SMSService.topupResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class topupResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int topupResult;
        
        public topupResponseBody() {
        }
        
        public topupResponseBody(int topupResult) {
            this.topupResult = topupResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBalance", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getBalanceRequestBody Body;
        
        public getBalanceRequest() {
        }
        
        public getBalanceRequest(CRM.SMSService.getBalanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBalanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        public getBalanceRequestBody() {
        }
        
        public getBalanceRequestBody(string clientNo, string clientPass) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBalanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBalanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getBalanceResponseBody Body;
        
        public getBalanceResponse() {
        }
        
        public getBalanceResponse(CRM.SMSService.getBalanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBalanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public decimal getBalanceResult;
        
        public getBalanceResponseBody() {
        }
        
        public getBalanceResponseBody(decimal getBalanceResult) {
            this.getBalanceResult = getBalanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBrandNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBrandNames", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getBrandNamesRequestBody Body;
        
        public getBrandNamesRequest() {
        }
        
        public getBrandNamesRequest(CRM.SMSService.getBrandNamesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBrandNamesRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        public getBrandNamesRequestBody() {
        }
        
        public getBrandNamesRequestBody(string clientNo, string clientPass) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getBrandNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getBrandNamesResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getBrandNamesResponseBody Body;
        
        public getBrandNamesResponse() {
        }
        
        public getBrandNamesResponse(CRM.SMSService.getBrandNamesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getBrandNamesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRM.SMSService.BrandNames[] getBrandNamesResult;
        
        public getBrandNamesResponseBody() {
        }
        
        public getBrandNamesResponseBody(CRM.SMSService.BrandNames[] getBrandNamesResult) {
            this.getBrandNamesResult = getBrandNamesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListSMSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListSMS", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getListSMSRequestBody Body;
        
        public getListSMSRequest() {
        }
        
        public getListSMSRequest(CRM.SMSService.getListSMSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListSMSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime toDate;
        
        public getListSMSRequestBody() {
        }
        
        public getListSMSRequestBody(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.fromDate = fromDate;
            this.toDate = toDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getListSMSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getListSMSResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getListSMSResponseBody Body;
        
        public getListSMSResponse() {
        }
        
        public getListSMSResponse(CRM.SMSService.getListSMSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getListSMSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRM.SMSService.SmsMessageItem[] getListSMSResult;
        
        public getListSMSResponseBody() {
        }
        
        public getListSMSResponseBody(CRM.SMSService.SmsMessageItem[] getListSMSResult) {
            this.getListSMSResult = getListSMSResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPhoneListRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPhoneList", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getPhoneListRequestBody Body;
        
        public getPhoneListRequest() {
        }
        
        public getPhoneListRequest(CRM.SMSService.getPhoneListRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPhoneListRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int MsgID;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public byte status;
        
        public getPhoneListRequestBody() {
        }
        
        public getPhoneListRequestBody(string clientNo, string clientPass, int MsgID, byte status) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.MsgID = MsgID;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getPhoneListResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getPhoneListResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getPhoneListResponseBody Body;
        
        public getPhoneListResponse() {
        }
        
        public getPhoneListResponse(CRM.SMSService.getPhoneListResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getPhoneListResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRM.SMSService.SmsPhoneListItem[] getPhoneListResult;
        
        public getPhoneListResponseBody() {
        }
        
        public getPhoneListResponseBody(CRM.SMSService.SmsPhoneListItem[] getPhoneListResult) {
            this.getPhoneListResult = getPhoneListResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTopupHistoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopupHistory", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getTopupHistoryRequestBody Body;
        
        public getTopupHistoryRequest() {
        }
        
        public getTopupHistoryRequest(CRM.SMSService.getTopupHistoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTopupHistoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string clientNo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string clientPass;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public System.DateTime fromDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime toDate;
        
        public getTopupHistoryRequestBody() {
        }
        
        public getTopupHistoryRequestBody(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate) {
            this.clientNo = clientNo;
            this.clientPass = clientPass;
            this.fromDate = fromDate;
            this.toDate = toDate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTopupHistoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getTopupHistoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public CRM.SMSService.getTopupHistoryResponseBody Body;
        
        public getTopupHistoryResponse() {
        }
        
        public getTopupHistoryResponse(CRM.SMSService.getTopupHistoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getTopupHistoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public CRM.SMSService.TopUpHistoryItem[] getTopupHistoryResult;
        
        public getTopupHistoryResponseBody() {
        }
        
        public getTopupHistoryResponseBody(CRM.SMSService.TopUpHistoryItem[] getTopupHistoryResult) {
            this.getTopupHistoryResult = getTopupHistoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface APISoapChannel : CRM.SMSService.APISoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class APISoapClient : System.ServiceModel.ClientBase<CRM.SMSService.APISoap>, CRM.SMSService.APISoap {
        
        public APISoapClient() {
        }
        
        public APISoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public APISoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public APISoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.aboutResponse CRM.SMSService.APISoap.about(CRM.SMSService.aboutRequest request) {
            return base.Channel.about(request);
        }
        
        public string about() {
            CRM.SMSService.aboutRequest inValue = new CRM.SMSService.aboutRequest();
            inValue.Body = new CRM.SMSService.aboutRequestBody();
            CRM.SMSService.aboutResponse retVal = ((CRM.SMSService.APISoap)(this)).about(inValue);
            return retVal.Body.aboutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.checkClientResponse CRM.SMSService.APISoap.checkClient(CRM.SMSService.checkClientRequest request) {
            return base.Channel.checkClient(request);
        }
        
        public int checkClient(string clientNo, string clientPass) {
            CRM.SMSService.checkClientRequest inValue = new CRM.SMSService.checkClientRequest();
            inValue.Body = new CRM.SMSService.checkClientRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            CRM.SMSService.checkClientResponse retVal = ((CRM.SMSService.APISoap)(this)).checkClient(inValue);
            return retVal.Body.checkClientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.changePasswordResponse CRM.SMSService.APISoap.changePassword(CRM.SMSService.changePasswordRequest request) {
            return base.Channel.changePassword(request);
        }
        
        public int changePassword(string clientNo, string oldPass, string newPass) {
            CRM.SMSService.changePasswordRequest inValue = new CRM.SMSService.changePasswordRequest();
            inValue.Body = new CRM.SMSService.changePasswordRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.oldPass = oldPass;
            inValue.Body.newPass = newPass;
            CRM.SMSService.changePasswordResponse retVal = ((CRM.SMSService.APISoap)(this)).changePassword(inValue);
            return retVal.Body.changePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.sendSMSResponse CRM.SMSService.APISoap.sendSMS(CRM.SMSService.sendSMSRequest request) {
            return base.Channel.sendSMS(request);
        }
        
        public int sendSMS(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string sender, bool isADs, string title, string message, string smsGUID, string guidName) {
            CRM.SMSService.sendSMSRequest inValue = new CRM.SMSService.sendSMSRequest();
            inValue.Body = new CRM.SMSService.sendSMSRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.listPhone = listPhone;
            inValue.Body.sender = sender;
            inValue.Body.isADs = isADs;
            inValue.Body.title = title;
            inValue.Body.message = message;
            inValue.Body.smsGUID = smsGUID;
            inValue.Body.guidName = guidName;
            CRM.SMSService.sendSMSResponse retVal = ((CRM.SMSService.APISoap)(this)).sendSMS(inValue);
            return retVal.Body.sendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.sendRandomSMSResponse CRM.SMSService.APISoap.sendRandomSMS(CRM.SMSService.sendRandomSMSRequest request) {
            return base.Channel.sendRandomSMS(request);
        }
        
        public int sendRandomSMS(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string title, string message, string smsGUID, string guidName) {
            CRM.SMSService.sendRandomSMSRequest inValue = new CRM.SMSService.sendRandomSMSRequest();
            inValue.Body = new CRM.SMSService.sendRandomSMSRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.listPhone = listPhone;
            inValue.Body.title = title;
            inValue.Body.message = message;
            inValue.Body.smsGUID = smsGUID;
            inValue.Body.guidName = guidName;
            CRM.SMSService.sendRandomSMSResponse retVal = ((CRM.SMSService.APISoap)(this)).sendRandomSMS(inValue);
            return retVal.Body.sendRandomSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.sendRandomSMSDemoResponse CRM.SMSService.APISoap.sendRandomSMSDemo(CRM.SMSService.sendRandomSMSDemoRequest request) {
            return base.Channel.sendRandomSMSDemo(request);
        }
        
        public int sendRandomSMSDemo(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string title, string message, string smsGUID, string guidName) {
            CRM.SMSService.sendRandomSMSDemoRequest inValue = new CRM.SMSService.sendRandomSMSDemoRequest();
            inValue.Body = new CRM.SMSService.sendRandomSMSDemoRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.listPhone = listPhone;
            inValue.Body.title = title;
            inValue.Body.message = message;
            inValue.Body.smsGUID = smsGUID;
            inValue.Body.guidName = guidName;
            CRM.SMSService.sendRandomSMSDemoResponse retVal = ((CRM.SMSService.APISoap)(this)).sendRandomSMSDemo(inValue);
            return retVal.Body.sendRandomSMSDemoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.checksendSMSResponse CRM.SMSService.APISoap.checksendSMS(CRM.SMSService.checksendSMSRequest request) {
            return base.Channel.checksendSMS(request);
        }
        
        public int checksendSMS(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string sender, bool isADs, string title, string message, string smsGUID, string guidName) {
            CRM.SMSService.checksendSMSRequest inValue = new CRM.SMSService.checksendSMSRequest();
            inValue.Body = new CRM.SMSService.checksendSMSRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.listPhone = listPhone;
            inValue.Body.sender = sender;
            inValue.Body.isADs = isADs;
            inValue.Body.title = title;
            inValue.Body.message = message;
            inValue.Body.smsGUID = smsGUID;
            inValue.Body.guidName = guidName;
            CRM.SMSService.checksendSMSResponse retVal = ((CRM.SMSService.APISoap)(this)).checksendSMS(inValue);
            return retVal.Body.checksendSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.checkSMSRandomResponse CRM.SMSService.APISoap.checkSMSRandom(CRM.SMSService.checkSMSRandomRequest request) {
            return base.Channel.checkSMSRandom(request);
        }
        
        public int checkSMSRandom(string clientNo, string clientPass, CRM.SMSService.ArrayOfString listPhone, string title, string message, string smsGUID, string guidName) {
            CRM.SMSService.checkSMSRandomRequest inValue = new CRM.SMSService.checkSMSRandomRequest();
            inValue.Body = new CRM.SMSService.checkSMSRandomRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.listPhone = listPhone;
            inValue.Body.title = title;
            inValue.Body.message = message;
            inValue.Body.smsGUID = smsGUID;
            inValue.Body.guidName = guidName;
            CRM.SMSService.checkSMSRandomResponse retVal = ((CRM.SMSService.APISoap)(this)).checkSMSRandom(inValue);
            return retVal.Body.checkSMSRandomResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.topupResponse CRM.SMSService.APISoap.topup(CRM.SMSService.topupRequest request) {
            return base.Channel.topup(request);
        }
        
        public int topup(string clientNo, string clientPass, decimal amount, string secureCode) {
            CRM.SMSService.topupRequest inValue = new CRM.SMSService.topupRequest();
            inValue.Body = new CRM.SMSService.topupRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.amount = amount;
            inValue.Body.secureCode = secureCode;
            CRM.SMSService.topupResponse retVal = ((CRM.SMSService.APISoap)(this)).topup(inValue);
            return retVal.Body.topupResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.getBalanceResponse CRM.SMSService.APISoap.getBalance(CRM.SMSService.getBalanceRequest request) {
            return base.Channel.getBalance(request);
        }
        
        public decimal getBalance(string clientNo, string clientPass) {
            CRM.SMSService.getBalanceRequest inValue = new CRM.SMSService.getBalanceRequest();
            inValue.Body = new CRM.SMSService.getBalanceRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            CRM.SMSService.getBalanceResponse retVal = ((CRM.SMSService.APISoap)(this)).getBalance(inValue);
            return retVal.Body.getBalanceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.getBrandNamesResponse CRM.SMSService.APISoap.getBrandNames(CRM.SMSService.getBrandNamesRequest request) {
            return base.Channel.getBrandNames(request);
        }
        
        public CRM.SMSService.BrandNames[] getBrandNames(string clientNo, string clientPass) {
            CRM.SMSService.getBrandNamesRequest inValue = new CRM.SMSService.getBrandNamesRequest();
            inValue.Body = new CRM.SMSService.getBrandNamesRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            CRM.SMSService.getBrandNamesResponse retVal = ((CRM.SMSService.APISoap)(this)).getBrandNames(inValue);
            return retVal.Body.getBrandNamesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.getListSMSResponse CRM.SMSService.APISoap.getListSMS(CRM.SMSService.getListSMSRequest request) {
            return base.Channel.getListSMS(request);
        }
        
        public CRM.SMSService.SmsMessageItem[] getListSMS(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate) {
            CRM.SMSService.getListSMSRequest inValue = new CRM.SMSService.getListSMSRequest();
            inValue.Body = new CRM.SMSService.getListSMSRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.fromDate = fromDate;
            inValue.Body.toDate = toDate;
            CRM.SMSService.getListSMSResponse retVal = ((CRM.SMSService.APISoap)(this)).getListSMS(inValue);
            return retVal.Body.getListSMSResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.getPhoneListResponse CRM.SMSService.APISoap.getPhoneList(CRM.SMSService.getPhoneListRequest request) {
            return base.Channel.getPhoneList(request);
        }
        
        public CRM.SMSService.SmsPhoneListItem[] getPhoneList(string clientNo, string clientPass, int MsgID, byte status) {
            CRM.SMSService.getPhoneListRequest inValue = new CRM.SMSService.getPhoneListRequest();
            inValue.Body = new CRM.SMSService.getPhoneListRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.MsgID = MsgID;
            inValue.Body.status = status;
            CRM.SMSService.getPhoneListResponse retVal = ((CRM.SMSService.APISoap)(this)).getPhoneList(inValue);
            return retVal.Body.getPhoneListResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CRM.SMSService.getTopupHistoryResponse CRM.SMSService.APISoap.getTopupHistory(CRM.SMSService.getTopupHistoryRequest request) {
            return base.Channel.getTopupHistory(request);
        }
        
        public CRM.SMSService.TopUpHistoryItem[] getTopupHistory(string clientNo, string clientPass, System.DateTime fromDate, System.DateTime toDate) {
            CRM.SMSService.getTopupHistoryRequest inValue = new CRM.SMSService.getTopupHistoryRequest();
            inValue.Body = new CRM.SMSService.getTopupHistoryRequestBody();
            inValue.Body.clientNo = clientNo;
            inValue.Body.clientPass = clientPass;
            inValue.Body.fromDate = fromDate;
            inValue.Body.toDate = toDate;
            CRM.SMSService.getTopupHistoryResponse retVal = ((CRM.SMSService.APISoap)(this)).getTopupHistory(inValue);
            return retVal.Body.getTopupHistoryResult;
        }
    }
}
